[package]
authors = [
  "Jorge Aparicio <jorge@japaric.io>",
  "Per Lindgren <per.lindgren@ltu.se>",
]
categories = [
    "data-structures",
    "no-std",
]
description = "`static` friendly data structures that don't require dynamic memory allocation"
documentation = "https://docs.rs/heapless"
keywords = [
    "static",
    "no-heap",
]
license = "MIT OR Apache-2.0"
name = "heapless"
repository = "https://github.com/japaric/heapless"
version = "0.2.7"

[dependencies]
untagged-option = "0.1.1"

[dev-dependencies]
scoped_threadpool = "0.1.8"
